---
Gemfile:
  optional:
    ':development':
      - gem: 'github_changelog_generator'
        git: 'https://github.com/skywinder/github-changelog-generator'
        ref: '20ee04ba1234e9e83eb2ffb5056e23d641c7a018'
        condition: "Gem::Version.new(RUBY_VERSION.dup) >= Gem::Version.new('2.2.2')"
      - gem: 'rspec-puppet-facts'
        version: '~> 1.7'
      - gem: 'puppet-blacksmith'
      - gem: 'rspec-puppet'
      - gem: 'puppet-strings'
      - gem: 'rgen'

Rakefile:
  requires:
      - 'puppet-lint/tasks/puppet-lint'
      - 'puppetlabs_spec_helper/rake_tasks'
  extras:
      - > 
          begin

            require 'puppet_blacksmith/rake_tasks'
            require 'puppet-strings/tasks'

          rescue LoadError

          end

